// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Stefan Hermann (CNC Kitchen) <stefan@cnckitchen.com>

//! WASM API for the Smart Infill Generator web app.
//!
//! One `Model` instance lives in a web worker and owns mesh, segmentation,
//! voxel grid, boundary conditions, and the last solution. Bulk data crosses
//! the boundary as typed arrays; small results as JSON strings.

use sig_core::attach::{assemble, check_problem, BcKind, BcSpec};
use sig_core::bins::{
    assign_bins_mass, cleanup_small_regions, cluster_levels, extract_iso, extract_region,
    taubin_smooth, RegionMesh,
};
use sig_core::mesh::TriMesh;
use sig_core::segment::{segment, Segmentation};
use sig_core::simp::{evaluate_cached, optimize_cached as simp_optimize, OptimizeParams};
use sig_core::solve::{
    active_nodes, pad_for_levels, solve_nodes_cached, SolveSettings, Solution, SolverCache,
};
use sig_core::stress::{cell_field, FieldKind};
use sig_core::threemf::{export_orca_3mf, export_stl_zip, import_3mf, weld};
use sig_core::voxel::VoxelGrid;
use wasm_bindgen::prelude::*;

/// Threaded builds expose `initThreadPool(n)` on the JS side; the worker
/// must await it before constructing a Model. Plain builds don't have it.
#[cfg(feature = "parallel")]
pub use wasm_bindgen_rayon::init_thread_pool;

const GRAVITY_MM_S2: [f64; 3] = [0.0, 0.0, -9810.0];

struct OptOutput {
    /// Smoothed regions (display + export); regenerated by resmooth_regions.
    regions: Vec<RegionMesh>,
    /// Raw marching-tets regions before smoothing (re-smoothing source).
    regions_raw: Vec<RegionMesh>,
    base_density: f64,
    /// Final per-design-cell binned density.
    cell_density: std::collections::HashMap<u32, f64>,
    /// Continuous (pre-binning) field for the density-threshold isosurface.
    design_cells: Vec<u32>,
    x_cont: Vec<f64>,
    /// Perimeter count the analysis skin assumed — exported as the part-level
    /// wall_loops so the print matches the simulation.
    perimeters: u32,
    /// Per-modifier sparse_infill_pattern for the export (binary mode's
    /// rectilinear/concentric solid fill); None = profile default.
    solid_pattern: Option<String>,
    summary: String,
}

/// Options for `Model::optimize`, passed as one JSON object from the worker.
#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase", default)]
struct OptimizeOpts {
    /// Target mean interior infill density in percent.
    budget_pct: f64,
    /// Calibrated infill law E/E0 = coeff·ρ^exponent of the chosen pattern —
    /// used for ALL stiffness evaluation (verification, baselines, stress).
    exponent: f64,
    coeff: f64,
    perimeters: u32,
    line_width: f64,
    smooth_iters: u32,
    n_bins: u32,
    /// Printable density band in percent. Graded default 10–70.
    floor_pct: f64,
    cap_pct: f64,
    /// Manual level override in percent; None/empty = auto placement.
    levels_pct: Option<Vec<f64>>,
    /// Binary (hollow/solid) mode: the OPTIMIZER runs with SIMP penalization
    /// p = 3 so the field converges toward {floor, 1} before quantization;
    /// evaluation still uses the calibrated law (exact at both endpoints).
    binary: bool,
    /// Solid-fill pattern for the export in binary mode.
    solid_pattern: Option<String>,
    /// "budget" = stiffest design at the given mean infill (one pass);
    /// "match" = LIGHTEST design as stiff as a uniform print at budget_pct —
    /// a guarded secant on the budget, each pass warm-started, until the
    /// BINNED design's compliance meets the uniform reference within 2%.
    goal: String,
}

impl Default for OptimizeOpts {
    fn default() -> Self {
        Self {
            budget_pct: 25.0,
            exponent: 1.5,
            coeff: 1.0,
            perimeters: 2,
            line_width: 0.45,
            smooth_iters: 15,
            n_bins: 3,
            floor_pct: 10.0,
            cap_pct: 70.0,
            levels_pct: None,
            binary: false,
            solid_pattern: None,
            goal: "budget".into(),
        }
    }
}

/// Options for `Model::solve_printed` — analyze the part AS PRINTED:
/// skin (perimeters × line width) solid, interior at a uniform infill
/// ratio through the calibrated pattern law.
#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase", default)]
struct PrintedOpts {
    infill_pct: f64,
    exponent: f64,
    coeff: f64,
    perimeters: u32,
    line_width: f64,
}

impl Default for PrintedOpts {
    fn default() -> Self {
        Self { infill_pct: 25.0, exponent: 1.5, coeff: 1.0, perimeters: 2, line_width: 0.45 }
    }
}

#[wasm_bindgen]
pub struct Model {
    /// Working mesh: display + segmentation + BC attachment + voxelization.
    /// Subdivided at load so deformed shapes can actually bend (a coarse STL
    /// face has no vertices to carry the curve).
    mesh: TriMesh,
    /// Original tessellation as imported — exported 3MFs carry this one.
    mesh_orig: TriMesh,
    /// Original-triangle index per working-mesh triangle. Segmentation runs
    /// on the original mesh and is mapped through this: subdivision creates
    /// T-junctions along shared edges (neighbors get different n), so
    /// segmenting the subdivided soup would fragment flat surfaces.
    parents: Vec<u32>,
    name: String,
    mesh_objects: usize,
    seg: Segmentation,
    bcs: Vec<BcSpec>,
    settings: SolveSettings,
    /// tonne/mm³
    density: f64,
    /// Tensile strength (MPa) of the solid material — safety-factor plot.
    strength: f64,
    /// Layer-adhesion strength (MPa): tension PERPENDICULAR to the layers
    /// (σzz, build direction Z-up). Drives the conservative SF variants.
    strength_z: f64,
    gravity_on: bool,
    target_cells: u32,
    /// Snap the voxel size to wall/k (0 = off) so the printed skin is
    /// resolved by an integer number of cell layers.
    snap_wall: f64,
    grid: Option<(VoxelGrid, usize)>, // padded grid + level count
    /// Reused solver hierarchy + warm start across solves (self-validating:
    /// falls back to a cold rebuild when grid/material/BCs/topology change).
    solver_cache: Option<SolverCache>,
    solution: Option<Solution>,
    /// Per-cell stiffness factors the CURRENT solution was computed with:
    /// None = plain solid solve (grid.scale), Some = binned-infill field.
    /// Stress evaluation must use the same eps as the solve.
    solution_eps: Option<Vec<f32>>,
    opt: Option<OptOutput>,
}

fn err(e: impl std::fmt::Display) -> JsValue {
    JsValue::from_str(&e.to_string())
}

/// Patch ids computed on the original mesh, carried onto the subdivided
/// working mesh (each child inherits its parent triangle's patch).
fn remap_segmentation(orig: &Segmentation, parents: &[u32]) -> Segmentation {
    Segmentation {
        patch_of_tri: parents.iter().map(|&p| orig.patch_of_tri[p as usize]).collect(),
        patch_count: orig.patch_count,
    }
}

#[wasm_bindgen]
impl Model {
    /// Parse STL (binary/ASCII) or 3MF (detected by zip magic); segment at
    /// 10° (fine patches pick better; the slider re-segments live).
    #[wasm_bindgen(constructor)]
    pub fn new(bytes: &[u8], name: &str) -> Result<Model, JsValue> {
        let (mesh_orig, mesh_objects) = if bytes.len() >= 2 && &bytes[..2] == b"PK" {
            import_3mf(bytes).map_err(err)?
        } else {
            (TriMesh::from_stl(bytes).map_err(err)?, 1)
        };
        // Refine the display/analysis tessellation: edges capped at ~1/60 of
        // the diagonal so deflection curves are visible on coarse STLs.
        // Dense meshes pass through unchanged (160k-triangle budget).
        let (mesh, parents) = match mesh_orig.bounds() {
            Some((lo, hi)) => {
                let diag = ((hi[0] - lo[0]).powi(2)
                    + (hi[1] - lo[1]).powi(2)
                    + (hi[2] - lo[2]).powi(2))
                .sqrt();
                mesh_orig.subdivided_with_parents(diag / 60.0, 160_000)
            }
            None => (mesh_orig.clone(), (0..mesh_orig.len() as u32).collect()),
        };
        let seg = remap_segmentation(&segment(&mesh_orig, 10.0), &parents);
        Ok(Model {
            mesh,
            mesh_orig,
            parents,
            name: name.to_string(),
            mesh_objects,
            seg,
            bcs: Vec::new(),
            settings: SolveSettings::default(),
            density: 1.24e-9,  // PLA
            strength: 50.0,    // PLA tensile, MPa
            strength_z: 35.0,  // PLA layer adhesion, MPa
            gravity_on: false,
            target_cells: 300_000,
            snap_wall: 0.0,
            grid: None,
            solver_cache: None,
            solution: None,
            solution_eps: None,
            opt: None,
        })
    }

    /// Number of mesh objects found in the imported file (UI warns when >1).
    pub fn mesh_object_count(&self) -> u32 {
        self.mesh_objects as u32
    }

    pub fn triangle_count(&self) -> u32 {
        self.mesh.len() as u32
    }

    /// Triangle soup positions, 9 floats per triangle (three.js non-indexed).
    pub fn positions(&self) -> Vec<f32> {
        let mut out = Vec::with_capacity(self.mesh.tris.len() * 9);
        for t in &self.mesh.tris {
            out.extend_from_slice(t);
        }
        out
    }

    /// Patch id per triangle.
    pub fn patch_ids(&self) -> Vec<u32> {
        self.seg.patch_of_tri.clone()
    }

    pub fn patch_count(&self) -> u32 {
        self.seg.patch_count as u32
    }

    /// Re-run segmentation with a different crease angle (degrees).
    pub fn resegment(&mut self, angle_deg: f64) {
        self.seg =
            remap_segmentation(&segment(&self.mesh_orig, angle_deg.clamp(1.0, 89.0)), &self.parents);
    }

    /// [lox, loy, loz, hix, hiy, hiz] in mm.
    pub fn bbox(&self) -> Vec<f64> {
        match self.mesh.bounds() {
            Some((lo, hi)) => vec![lo[0], lo[1], lo[2], hi[0], hi[1], hi[2]],
            None => vec![0.0; 6],
        }
    }

    /// e0 in MPa, density in g/cm³, strengths in MPa (in-layer tensile and
    /// layer-adhesion / cross-layer).
    pub fn set_material(
        &mut self,
        e0: f64,
        nu: f64,
        density_g_cm3: f64,
        strength_mpa: f64,
        strength_z_mpa: f64,
    ) {
        self.settings.e0 = e0;
        self.settings.nu = nu;
        self.density = density_g_cm3 * 1e-9;
        self.strength = strength_mpa.max(0.1);
        self.strength_z = strength_z_mpa.max(0.1);
        self.solution = None;
        self.opt = None;
    }

    pub fn set_gravity(&mut self, on: bool) {
        self.gravity_on = on;
        self.solution = None;
        self.opt = None;
    }

    pub fn set_resolution(&mut self, target_cells: u32) {
        if target_cells != self.target_cells {
            self.target_cells = target_cells.clamp(10_000, 4_000_000);
            self.grid = None;
            self.solution = None;
        self.opt = None;
        }
    }

    /// Snap the voxel size to an integer fraction of the wall thickness
    /// (h = wall/k) so the printed skin is exactly k cell layers on flat
    /// faces. 0 disables. Changing the value invalidates grid and results.
    pub fn set_snap_wall(&mut self, wall_mm: f64) {
        let w = if wall_mm > 0.0 { wall_mm.clamp(0.2, 5.0) } else { 0.0 };
        if (w - self.snap_wall).abs() > 1e-9 {
            self.snap_wall = w;
            self.grid = None;
            self.solution = None;
            self.solution_eps = None;
            self.opt = None;
        }
    }

    pub fn clear_bcs(&mut self) {
        self.bcs.clear();
        self.solution = None;
        self.opt = None;
    }

    pub fn add_fixed(&mut self, tris: &[u32]) {
        self.bcs.push(BcSpec { kind: BcKind::Fixed, tris: tris.to_vec() });
        self.solution = None;
        self.opt = None;
    }

    pub fn add_frictionless(&mut self, tris: &[u32]) {
        self.bcs.push(BcSpec { kind: BcKind::Frictionless, tris: tris.to_vec() });
        self.solution = None;
        self.opt = None;
    }

    /// Elastic ("soft") support: Winkler foundation, bedding modulus k in
    /// N/mm³ (surface pressure per unit displacement, σ = k·u).
    pub fn add_elastic(&mut self, tris: &[u32], k: f64) {
        self.bcs.push(BcSpec { kind: BcKind::Elastic(k.clamp(1e-4, 1e7)), tris: tris.to_vec() });
        self.solution = None;
        self.opt = None;
    }

    pub fn add_force(&mut self, tris: &[u32], fx: f64, fy: f64, fz: f64) {
        self.bcs.push(BcSpec { kind: BcKind::Force([fx, fy, fz]), tris: tris.to_vec() });
        self.solution = None;
        self.opt = None;
    }

    pub fn add_pressure(&mut self, tris: &[u32], mpa: f64) {
        self.bcs.push(BcSpec { kind: BcKind::Pressure(mpa), tris: tris.to_vec() });
        self.solution = None;
        self.opt = None;
    }

    fn ensure_grid(&mut self) -> Result<(), JsValue> {
        if self.grid.is_some() {
            return Ok(());
        }
        let (lo, hi) = self.mesh.bounds().ok_or_else(|| err("empty mesh"))?;
        let vol = (hi[0] - lo[0]).max(1e-6) * (hi[1] - lo[1]).max(1e-6) * (hi[2] - lo[2]).max(1e-6);
        let h = sig_core::voxel::pick_voxel_size(vol, self.target_cells as f64, self.snap_wall);
        let grid = VoxelGrid::voxelize(&self.mesh, h);
        if grid.solid_count() == 0 {
            return Err(err("voxelization produced no solid cells — model too thin for this resolution"));
        }
        let (padded, levels) = pad_for_levels(&grid, self.settings.max_levels);
        self.grid = Some((padded, levels));
        Ok(())
    }

    /// JSON: { nx, ny, nz, h, cells, solid }
    pub fn voxel_info(&mut self) -> Result<String, JsValue> {
        self.ensure_grid()?;
        let (g, _) = self.grid.as_ref().unwrap();
        Ok(serde_json::json!({
            "nx": g.nx, "ny": g.ny, "nz": g.nz, "h": g.h,
            "cells": g.cell_count(), "solid": g.solid_count(),
        })
        .to_string())
    }

    fn gravity_arg(&self) -> Option<([f64; 3], f64)> {
        if self.gravity_on {
            Some((GRAVITY_MM_S2, self.density))
        } else {
            None
        }
    }

    /// Island + rigid-body-mode check. JSON CheckReport.
    pub fn check(&mut self) -> Result<String, JsValue> {
        self.ensure_grid()?;
        let (grid, _) = self.grid.as_ref().unwrap();
        let asm = assemble(&self.mesh, grid, &self.bcs, self.gravity_arg(), &self.settings)
            .map_err(err)?;
        let report = check_problem(grid, &asm);
        let comps: Vec<serde_json::Value> = report
            .components
            .iter()
            .map(|c| {
                serde_json::json!({
                    "cells": c.cells,
                    "constrained": c.constrained,
                    "lambdaRatio": c.lambda_ratio,
                    "hasLoads": c.has_loads,
                    "mode": c.mode.as_ref().map(|m| serde_json::json!({
                        "t": m.t, "r": m.r, "center": m.center,
                    })),
                })
            })
            .collect();
        Ok(serde_json::json!({
            "ok": report.ok,
            "islandCount": report.island_count,
            "components": comps,
        })
        .to_string())
    }

    /// Run the static solve. JSON: { iterations, relResidual, maxDisplacement }.
    pub fn solve(&mut self) -> Result<String, JsValue> {
        self.ensure_grid()?;
        let (grid, levels) = self.grid.as_ref().unwrap();
        let asm = assemble(&self.mesh, grid, &self.bcs, self.gravity_arg(), &self.settings)
            .map_err(err)?;
        let report = check_problem(grid, &asm);
        if !report.ok {
            return Err(err("model is under-constrained — run check() for details"));
        }
        let sol = solve_nodes_cached(&mut self.solver_cache, grid, *levels, &asm.problem, &self.settings)
            .map_err(err)?;
        let out = serde_json::json!({
            "iterations": sol.iterations,
            "relResidual": sol.rel_residual,
            "converged": sol.converged,
            "maxDisplacement": sol.max_displacement(),
            // Per-MGCG-iteration relative residual (element 0 = initial) —
            // the nerd-log convergence plot.
            "residuals": sol.residuals.clone(),
        })
        .to_string();
        self.solution = Some(sol);
        self.solution_eps = None; // plain solid solve: eps = grid.scale
        Ok(out)
    }

    /// Analyze the part AS PRINTED: skin (perimeters × line width) at 100%,
    /// interior at a uniform infill ratio through the calibrated pattern law.
    /// Same machinery as the optimizer's verification solves — the accuracy
    /// is the accuracy of the calibrated E(ρ) curve. Stress/SF fields use
    /// the stored eps, so the safety factor of the printed part falls out.
    /// JSON: solve() fields + massGrams/massSolidGrams/skinCells/
    /// interiorCells/skinLayers for the results dock.
    pub fn solve_printed(&mut self, opts_json: &str) -> Result<String, JsValue> {
        let opts: PrintedOpts = serde_json::from_str(opts_json).map_err(err)?;
        self.ensure_grid()?;
        let (grid, levels) = self.grid.as_ref().unwrap();
        let asm = assemble(&self.mesh, grid, &self.bcs, self.gravity_arg(), &self.settings)
            .map_err(err)?;
        let report = check_problem(grid, &asm);
        if !report.ok {
            return Err(err("model is under-constrained — run check() for details"));
        }
        let eval_exp = opts.exponent.clamp(1.0, 3.5);
        let eval_coeff = opts.coeff.clamp(0.05, 2.0);
        let perimeters = opts.perimeters.clamp(1, 8);
        let wall_mm = (perimeters as f64 * opts.line_width.clamp(0.1, 1.5)).clamp(0.2, 5.0);
        let infill = (opts.infill_pct / 100.0).clamp(0.01, 1.0);
        // A part thinner than the wall everywhere simply prints solid —
        // design is empty and the solve degenerates to the solid case.
        let (skin, design) = sig_core::simp::classify_cells(grid, wall_mm);
        let x = vec![infill; design.len()];
        let eps = sig_core::simp::build_eps(grid, &skin, &design, &x, eval_exp, eval_coeff);
        let (sol, _compliance) = sig_core::simp::solve_with_eps_cached(
            &mut self.solver_cache,
            grid,
            *levels,
            &asm.problem,
            &self.settings,
            eps.clone(),
        )
        .map_err(err)?;
        // Mass at these print settings: solid skin + interior at the ratio.
        let cell_vol = grid.h * grid.h * grid.h;
        let n_skin = skin.len() as f64;
        let n_design = design.len() as f64;
        let mass = (n_skin + infill * n_design) * cell_vol * self.density * 1e6;
        let mass_solid = (n_skin + n_design) * cell_vol * self.density * 1e6;
        let out = serde_json::json!({
            "iterations": sol.iterations,
            "relResidual": sol.rel_residual,
            "converged": sol.converged,
            "maxDisplacement": sol.max_displacement(),
            "residuals": sol.residuals.clone(),
            "massGrams": mass,
            "massSolidGrams": mass_solid,
            "skinCells": skin.len(),
            "interiorCells": design.len(),
            // Cell layers the grid resolves the skin with (k after snapping).
            "skinLayers": (wall_mm / grid.h).round().max(1.0) as u32,
        })
        .to_string();
        self.solution = Some(sol);
        self.solution_eps = Some(eps);
        Ok(out)
    }

    /// Displacement vector (mm) per soup vertex: 9 floats per triangle.
    pub fn vertex_displacements(&self) -> Result<Vec<f32>, JsValue> {
        let sol = self.solution.as_ref().ok_or_else(|| err("no solution — call solve() first"))?;
        let mut out = Vec::with_capacity(self.mesh.tris.len() * 9);
        for t in &self.mesh.tris {
            for v in 0..3 {
                let p = [t[3 * v] as f64, t[3 * v + 1] as f64, t[3 * v + 2] as f64];
                let u = sol.sample_displacement(p);
                out.extend_from_slice(&[u[0] as f32, u[1] as f32, u[2] as f32]);
            }
        }
        Ok(out)
    }

    /// Sample a density field (cell -> density map) at every soup vertex,
    /// probing slightly inward and falling back to nearby solid cells.
    fn sample_cell_field(&self, grid: &VoxelGrid, field: &std::collections::HashMap<u32, f64>) -> Vec<f32> {
        let (nx, ny, nz) = (grid.nx, grid.ny, grid.nz);
        let h = grid.h;
        let cell_at = |p: [f64; 3]| -> Option<usize> {
            let cx = ((p[0] - grid.origin[0]) / h).floor() as i64;
            let cy = ((p[1] - grid.origin[1]) / h).floor() as i64;
            let cz = ((p[2] - grid.origin[2]) / h).floor() as i64;
            if cx < 0 || cy < 0 || cz < 0 || cx >= nx as i64 || cy >= ny as i64 || cz >= nz as i64 {
                return None;
            }
            Some(((cz as usize) * ny + cy as usize) * nx + cx as usize)
        };
        let mut out = Vec::with_capacity(self.mesh.tris.len() * 3);
        for t in &self.mesh.tris {
            for v in 0..3 {
                let p = [t[3 * v] as f64, t[3 * v + 1] as f64, t[3 * v + 2] as f64];
                // Search a small neighborhood: prefer a design cell, else skin.
                let mut val = 1.0f64;
                let mut found = false;
                'search: for r in 0..3i64 {
                    for dz in -r..=r {
                        for dy in -r..=r {
                            for dx in -r..=r {
                                let q = [
                                    p[0] + dx as f64 * h,
                                    p[1] + dy as f64 * h,
                                    p[2] + dz as f64 * h,
                                ];
                                if let Some(ci) = cell_at(q) {
                                    if let Some(&x) = field.get(&(ci as u32)) {
                                        val = x;
                                        found = true;
                                        break 'search;
                                    }
                                    if !found && grid.scale[ci] > 0.0 {
                                        found = true;
                                        val = 1.0; // skin
                                    }
                                }
                            }
                        }
                    }
                    if found {
                        break;
                    }
                }
                out.push(val as f32);
            }
        }
        out
    }

    /// Run the density optimization + binning + verification. `opts_json`
    /// is an OptimizeOpts object; budgetPct is the target mean INFILL
    /// density of the interior in percent — the number a user compares to a
    /// slicer's uniform infill setting (the solid skin is on top of it).
    /// Progress gets
    /// called per iteration with (jsonString, Float32Array vertexDensity,
    /// Float32Array skeletonPositions, Uint32Array skeletonIndices) — the
    /// skeleton is the evolving isosurface of cells denser than 40%.
    /// The perimeter count is also written into the
    /// exported 3MF as the PART's wall_loops (modifiers never pin walls), so
    /// the print matches the analysis assumption.
    pub fn optimize(
        &mut self,
        opts_json: &str,
        progress: &js_sys::Function,
    ) -> Result<String, JsValue> {
        self.ensure_grid()?;
        let opts: OptimizeOpts = serde_json::from_str(opts_json).map_err(err)?;
        // Calibrated pattern law: every stiffness EVALUATION uses this.
        let eval_exp = opts.exponent.clamp(1.0, 3.5);
        let eval_coeff = opts.coeff.clamp(0.05, 2.0);
        // Optimizer law: binary mode swaps in SIMP penalization p=3 so the
        // continuous field converges toward {floor, solid} — quantizing a
        // physically-graded (n≈1.5) field straight to two levels would
        // throw away far more.
        let (opt_exp, opt_coeff) = if opts.binary { (3.0, 1.0) } else { (eval_exp, eval_coeff) };
        let floor = (opts.floor_pct / 100.0).clamp(0.01, 0.5);
        let cap = (opts.cap_pct / 100.0).clamp(floor + 0.05, 1.0);
        let budget_pct = opts.budget_pct;
        let perimeters = opts.perimeters.clamp(1, 8);
        let wall_mm = perimeters as f64 * opts.line_width.clamp(0.1, 1.5);
        let smooth_iters = (opts.smooth_iters as usize).min(60);
        let n_bins = (opts.n_bins as usize).clamp(2, 4);

        // Assemble + check before burning time.
        let (grid, levels) = self.grid.as_ref().unwrap();
        let asm = assemble(&self.mesh, grid, &self.bcs, self.gravity_arg(), &self.settings)
            .map_err(err)?;
        let report = check_problem(grid, &asm);
        if !report.ok {
            return Err(err("model is under-constrained — fix the setup first (run Check)"));
        }

        let params = OptimizeParams {
            // Budget = target mean INFILL density of the interior — the
            // engine clamps it to the printable [floor, cap] band.
            budget: (budget_pct / 100.0).clamp(0.01, 1.0),
            exponent: opt_exp,
            coeff: opt_coeff,
            floor,
            cap,
            wall_mm: wall_mm.clamp(0.2, 5.0),
            // Cap is a safety net; the change-based convergence criterion
            // normally stops the loop earlier.
            max_iter: 40,
            ..Default::default()
        };

        let mesh = &self.mesh;
        let max_iter = params.max_iter;
        // Borrow self fields disjointly for the progress closure.
        let tris = &mesh.tris;
        // Isosurface threshold for the live "shape emerging" view.
        const SKEL_DENSITY: f64 = 0.4;

        // ---- goal handling ----
        // "match": find the LIGHTEST design as stiff as a uniform print at
        // the reference percentage. One tight uniform solve sets the target
        // compliance; a guarded secant then walks the budget (each pass
        // warm-started from the previous design) until the BINNED design
        // lands within tolerance. Compliance is smooth and monotone in the
        // budget, so a handful of passes suffice.
        let goal_match = opts.goal == "match";
        const MATCH_TOL: f64 = 0.02;
        let max_passes: usize = if goal_match { 5 } else { 1 };
        let ref_frac = (budget_pct / 100.0).clamp(params.floor, params.cap);
        let mut c_target = 0.0f64;
        if goal_match {
            let (skin_t, design_t) = sig_core::simp::classify_cells(grid, params.wall_mm);
            if design_t.is_empty() {
                return Err(err(
                    "part is thinner than the wall thickness everywhere — nothing to optimize (it prints solid)",
                ));
            }
            let x_ref = vec![ref_frac; design_t.len()];
            let (c_ref, _, _) = evaluate_cached(
                &mut self.solver_cache, grid, *levels, &asm.problem, &self.settings, &skin_t,
                &design_t, &x_ref, eval_exp, eval_coeff,
            )
            .map_err(err)?;
            c_target = c_ref;
        }

        let pass_no = std::cell::Cell::new(1usize);
        let mut budget_k = if goal_match {
            // Optimized designs typically match uniform stiffness at
            // ~70–85% of the mass — start the search there.
            (ref_frac * 0.8).max(params.floor)
        } else {
            (budget_pct / 100.0).clamp(0.01, 1.0)
        };
        let (mut lo_b, mut hi_b) = (params.floor, ref_frac);
        let mut warm_x: Option<Vec<f64>> = None;
        let mut warm_u: Option<Vec<f64>> = None;
        let mut pass_trace: Vec<(f64, f64)> = Vec::new();
        let mut total_iters = 0usize;
        let (result, centers, bins, x_binned, c_binned, u_binned) = loop {
            let params_k = OptimizeParams { budget: budget_k, ..params };
            let result = simp_optimize(
                &mut self.solver_cache,
                grid,
                *levels,
                &asm.problem,
                &self.settings,
                &params_k,
                warm_x.as_deref(),
                warm_u.as_deref(),
                |p, x_phys, design_cells| {
                    let mut field: std::collections::HashMap<u32, f64> =
                        std::collections::HashMap::with_capacity(design_cells.len());
                    for (k, &c) in design_cells.iter().enumerate() {
                        field.insert(c, x_phys[k]);
                    }
                    // Inline vertex sampling (cannot call &self methods here).
                    let vd = sample_field_static(tris, grid, &field);
                    // Evolving dense-core isosurface so the user watches the
                    // optimized shape gain detail iteration by iteration.
                    // Built on the CONTINUOUS filtered field — the level set
                    // is smooth; a binary per-cell indicator grows tent
                    // spikes wherever a single cell crosses the threshold.
                    let value = |ci: usize| field.get(&(ci as u32)).copied().unwrap_or(0.0);
                    let mut skel = extract_iso(grid, &value, SKEL_DENSITY);
                    taubin_smooth(&mut skel.positions, &skel.indices, 3);
                    let skel_density = sample_points_static(&skel.positions, grid, &field);
                    let json = serde_json::json!({
                        "iteration": p.iteration,
                        "maxIter": max_iter,
                        "pass": pass_no.get(),
                        "passes": max_passes,
                        "budgetNow": params_k.budget,
                        "compliance": p.compliance,
                        "massFrac": p.mass_frac,
                        "meanInfill": p.mean_infill,
                        "change": p.change,
                        "meanChange": p.mean_change,
                        "innerIters": p.inner_iters,
                        "innerRes": p.inner_residual,
                    })
                    .to_string();
                    let args = js_sys::Array::of5(
                        &JsValue::from_str(&json),
                        &js_sys::Float32Array::from(vd.as_slice()),
                        &js_sys::Float32Array::from(skel.positions.as_slice()),
                        &js_sys::Uint32Array::from(skel.indices.as_slice()),
                        &js_sys::Float32Array::from(skel_density.as_slice()),
                    );
                    let _ = progress.apply(&JsValue::NULL, &args);
                },
            )
            .map_err(err)?;
            total_iters += result.iterations;

            // ---- bins ----
            // Level placement: manual override (user levels / binary
            // {floor, 1}) when given, otherwise auto — floor pinned ("just
            // so it prints"), upper levels from strain-energy-weighted
            // clustering in stiffness space (the convex infill law makes
            // dense infill more efficient per gram, so load-bearing levels
            // land high). Assignment re-meets the budget via the anchored
            // bisection.
            let centers: Vec<f64> = match &opts.levels_pct {
                Some(user) if !user.is_empty() => {
                    let mut l: Vec<f64> =
                        user.iter().map(|&p| (p / 100.0).clamp(0.01, 1.0)).collect();
                    l.sort_by(|a, b| a.partial_cmp(b).unwrap());
                    l.dedup_by(|a, b| (*a - *b).abs() < 0.005);
                    l
                }
                _ => cluster_levels(
                    &result.x, &result.se, n_bins, eval_exp, eval_coeff, params.floor, params.cap,
                ),
            };
            let target_mean = result.x.iter().sum::<f64>() / result.x.len().max(1) as f64;
            let mut bins =
                assign_bins_mass(&result.x, &result.se, &centers, eval_exp, eval_coeff, target_mean);
            let min_cells = (result.design_cells.len() / 500).max(30);
            cleanup_small_regions(grid, &result.design_cells, &mut bins, centers.len(), min_cells);
            let x_binned: Vec<f64> = bins.iter().map(|&b| centers[b as usize]).collect();

            // Verification solve of the binned design (calibrated law);
            // warm-started from the optimizer's displacement via the cache.
            let (c_b, _maxd, u_b) = evaluate_cached(
                &mut self.solver_cache, grid, *levels, &asm.problem, &self.settings,
                &result.skin_cells, &result.design_cells, &x_binned, eval_exp, eval_coeff,
            )
            .map_err(err)?;
            pass_trace.push((budget_k, c_b));

            if !goal_match {
                break (result, centers, bins, x_binned, c_b, u_b);
            }
            // dev > 0: too compliant (needs more material); < 0: too stiff.
            let dev = c_b / c_target - 1.0;
            if dev.abs() <= MATCH_TOL || pass_no.get() >= max_passes || hi_b - lo_b < 0.005 {
                break (result, centers, bins, x_binned, c_b, u_b);
            }
            if dev > 0.0 {
                lo_b = lo_b.max(budget_k);
            } else {
                hi_b = hi_b.min(budget_k);
            }
            // Guarded secant on the last two passes; bisection fallback.
            let n = pass_trace.len();
            let mut next = if n >= 2 {
                let (b1, c1) = pass_trace[n - 2];
                let (b2, c2) = pass_trace[n - 1];
                if (c1 - c2).abs() > 1e-12 {
                    b2 + (c_target - c2) * (b1 - b2) / (c1 - c2)
                } else {
                    0.5 * (lo_b + hi_b)
                }
            } else {
                0.5 * (lo_b + hi_b)
            };
            if !(next > lo_b + 0.002 && next < hi_b - 0.002) {
                next = 0.5 * (lo_b + hi_b);
            }
            budget_k = next.clamp(params.floor, params.cap);
            warm_x = Some(result.x.clone());
            warm_u = Some(result.u.clone());
            pass_no.set(pass_no.get() + 1);
        };

        let mean_binned = x_binned.iter().sum::<f64>() / x_binned.len().max(1) as f64;
        let x_uniform = vec![mean_binned; x_binned.len()];
        let (c_uniform, _, _) = evaluate_cached(
            &mut self.solver_cache, grid, *levels, &asm.problem, &self.settings,
            &result.skin_cells, &result.design_cells, &x_uniform, eval_exp, eval_coeff,
        )
        .map_err(err)?;
        let x_solid = vec![1.0; x_binned.len()];
        let (c_solid, _, _) = evaluate_cached(
            &mut self.solver_cache, grid, *levels, &asm.problem, &self.settings,
            &result.skin_cells, &result.design_cells, &x_solid, eval_exp, eval_coeff,
        )
        .map_err(err)?;

        // Solution object for the deformed view.
        let (mx, my, mz) = (grid.nx + 1, grid.ny + 1, grid.nz + 1);
        let mut max_disp = 0f64;
        for n in 0..mx * my * mz {
            let m = u_binned[3 * n] * u_binned[3 * n]
                + u_binned[3 * n + 1] * u_binned[3 * n + 1]
                + u_binned[3 * n + 2] * u_binned[3 * n + 2];
            max_disp = max_disp.max(m);
        }
        max_disp = max_disp.sqrt();
        // Stress evaluation needs the eps the verification solve used.
        self.solution_eps = Some(sig_core::simp::build_eps(
            grid,
            &result.skin_cells,
            &result.design_cells,
            &x_binned,
            eval_exp,
            eval_coeff,
        ));
        self.solution = Some(Solution {
            u: u_binned.iter().map(|&v| v as f32).collect(),
            mx,
            my,
            mz,
            h: grid.h,
            origin: grid.origin,
            active: active_nodes(grid),
            iterations: result.iterations,
            rel_residual: 0.0,
            converged: true,
            residuals: Vec::new(),
        });

        // ---- regions (bins above base) ----
        let mut bin_of_cell: std::collections::HashMap<u32, u8> = Default::default();
        for (i, &c) in result.design_cells.iter().enumerate() {
            bin_of_cell.insert(c, bins[i]);
        }
        let mut regions_raw = Vec::new();
        for level in 1..centers.len() {
            let inside = |ci: usize| -> bool {
                bin_of_cell.get(&(ci as u32)).map_or(false, |&b| b as usize >= level)
            };
            let mut r = extract_region(grid, &inside, 0.4);
            if r.indices.is_empty() {
                continue;
            }
            r.density = centers[level];
            regions_raw.push(r);
        }
        let regions = smooth_regions(&regions_raw, smooth_iters);

        // ---- mass + summary ----
        let cell_vol = grid.h * grid.h * grid.h;
        let n_skin = result.skin_cells.len() as f64;
        let n_solid = n_skin + result.design_cells.len() as f64;
        let grams = |interior: f64| (n_skin + interior) * cell_vol * self.density * 1e6;
        let mass_part = grams(x_binned.iter().sum::<f64>());
        let mass_solid = grams(result.design_cells.len() as f64);
        let mass_frac = (n_skin + x_binned.iter().sum::<f64>()) / n_solid;

        let bin_counts: Vec<usize> =
            (0..centers.len()).map(|c| bins.iter().filter(|&&b| b as usize == c).count()).collect();
        let mut summary_v = serde_json::json!({
            "iterations": total_iters,
            "converged": result.converged,
            "bins": centers.iter().zip(&bin_counts).map(|(&d, &n)| serde_json::json!({
                "density": d, "cells": n,
            })).collect::<Vec<_>>(),
            "baseDensity": centers[0],
            "regionCount": regions.len(),
            "massGrams": mass_part,
            "massSolidGrams": mass_solid,
            "massFrac": mass_frac,
            // Achieved mean infill of the binned layout — the uniform-print
            // percentage the comparison card references ("vs X% uniform").
            "meanInfill": mean_binned,
            // Requested budget after printable-floor/cap clamping.
            "targetInfill": result.effective_budget,
            "stiffnessVsSolid": c_solid / c_binned,
            "gainVsUniform": c_uniform / c_binned - 1.0,
            "maxDisplacement": max_disp,
            "binary": opts.binary,
            "goal": if goal_match { "match" } else { "budget" },
            "passes": pass_trace.len(),
        });
        if goal_match {
            let o = summary_v.as_object_mut().unwrap();
            o.insert("refUniformPct".into(), serde_json::json!(ref_frac * 100.0));
            o.insert("targetCompliance".into(), serde_json::json!(c_target));
            o.insert("achievedCompliance".into(), serde_json::json!(c_binned));
            o.insert("matchDeviation".into(), serde_json::json!(c_binned / c_target - 1.0));
            // Mass of the uniform reference print (same skin, ref% interior).
            o.insert(
                "massUniformRefGrams".into(),
                serde_json::json!(grams(ref_frac * result.design_cells.len() as f64)),
            );
            o.insert(
                "passTrace".into(),
                serde_json::json!(pass_trace
                    .iter()
                    .map(|&(b, c)| serde_json::json!({"budget": b, "compliance": c}))
                    .collect::<Vec<_>>()),
            );
        }
        let summary = summary_v.to_string();

        let mut field: std::collections::HashMap<u32, f64> = Default::default();
        for (i, &c) in result.design_cells.iter().enumerate() {
            field.insert(c, x_binned[i]);
        }
        self.opt = Some(OptOutput {
            regions,
            regions_raw,
            base_density: centers[0],
            cell_density: field,
            design_cells: result.design_cells,
            x_cont: result.x,
            perimeters,
            solid_pattern: opts.solid_pattern.clone(),
            summary: summary.clone(),
        });
        Ok(summary)
    }

    /// Re-apply Taubin smoothing to the extracted regions (live preview of
    /// the smoothing slider). Affects display AND subsequent exports.
    pub fn resmooth_regions(&mut self, iters: u32) -> Result<(), JsValue> {
        let opt = self.opt.as_mut().ok_or_else(|| err("no optimization result"))?;
        opt.regions = smooth_regions(&opt.regions_raw, (iters as usize).min(60));
        Ok(())
    }

    /// Isosurface of the final continuous density field at `threshold`
    /// (0..1): everything denser than the threshold. Returns
    /// [positions f32, indices u32, per-vertex density f32] for the
    /// cutaway view (colored with the density legend ramp).
    pub fn density_isosurface(&self, threshold: f64) -> Result<js_sys::Array, JsValue> {
        let opt = self.opt.as_ref().ok_or_else(|| err("no optimization result"))?;
        let (grid, _) = self.grid.as_ref().ok_or_else(|| err("no grid"))?;
        let mut field: std::collections::HashMap<u32, f64> =
            std::collections::HashMap::with_capacity(opt.design_cells.len());
        for (i, &c) in opt.design_cells.iter().enumerate() {
            field.insert(c, opt.x_cont[i]);
        }
        let t = threshold.clamp(0.0, 1.0);
        // Continuous level set of the filtered field — smooth by nature.
        let value = |ci: usize| field.get(&(ci as u32)).copied().unwrap_or(0.0);
        let mut r = extract_iso(grid, &value, t);
        taubin_smooth(&mut r.positions, &r.indices, 3);
        let density = sample_points_static(&r.positions, grid, &field);
        Ok(js_sys::Array::of3(
            &js_sys::Float32Array::from(r.positions.as_slice()),
            &js_sys::Uint32Array::from(r.indices.as_slice()),
            &js_sys::Float32Array::from(density.as_slice()),
        ))
    }

    pub fn region_count(&self) -> u32 {
        self.opt.as_ref().map_or(0, |o| o.regions.len() as u32)
    }

    pub fn region_density(&self, i: u32) -> f64 {
        self.opt.as_ref().and_then(|o| o.regions.get(i as usize)).map_or(0.0, |r| r.density)
    }

    pub fn region_positions(&self, i: u32) -> Vec<f32> {
        self.opt
            .as_ref()
            .and_then(|o| o.regions.get(i as usize))
            .map_or(Vec::new(), |r| r.positions.clone())
    }

    pub fn region_indices(&self, i: u32) -> Vec<u32> {
        self.opt
            .as_ref()
            .and_then(|o| o.regions.get(i as usize))
            .map_or(Vec::new(), |r| r.indices.clone())
    }

    /// Final binned density per soup vertex (density view).
    pub fn vertex_density(&self) -> Result<Vec<f32>, JsValue> {
        let opt = self.opt.as_ref().ok_or_else(|| err("no optimization result"))?;
        let (grid, _) = self.grid.as_ref().ok_or_else(|| err("no grid"))?;
        Ok(self.sample_cell_field(grid, &opt.cell_density))
    }

    /// Per-cell scalar values of a result field on the padded grid (valid
    /// where grid.scale > 0), evaluated with the eps the solve actually used.
    fn cell_values(&self, kind: &str) -> Result<Vec<f32>, JsValue> {
        let sol =
            self.solution.as_ref().ok_or_else(|| err("no solution — run Solve or Optimize"))?;
        let (grid, _) = self.grid.as_ref().ok_or_else(|| err("no grid"))?;
        let scale_eps;
        let eps: &[f32] = match &self.solution_eps {
            Some(e) => e,
            None => {
                scale_eps = grid.scale.clone();
                &scale_eps
            }
        };
        // Safety factors: allowable = strength × the SAME relative factor as
        // the stiffness (Gibson–Ashby, first order; the skin carries full
        // strength). "sfm" checks the material against σ_vM; "sfz" checks
        // layer adhesion against TENSION across the layers (σzz > 0 only —
        // compression doesn't delaminate); "sf" is the per-cell worst of
        // both. All capped at 99.
        let sf_material = || -> Vec<f32> {
            let mut c = cell_field(
                grid, &sol.u, self.settings.e0, self.settings.nu, eps, FieldKind::VonMises,
            );
            for (i, v) in c.iter_mut().enumerate() {
                let allow = self.strength as f32 * eps[i];
                *v = (allow / v.max(1e-9)).min(99.0);
            }
            c
        };
        let sf_layer = || -> Result<Vec<f32>, JsValue> {
            let szz = FieldKind::parse("szz").ok_or_else(|| err("szz field missing"))?;
            let mut c =
                cell_field(grid, &sol.u, self.settings.e0, self.settings.nu, eps, szz);
            for (i, v) in c.iter_mut().enumerate() {
                let allow = self.strength_z as f32 * eps[i];
                *v = if *v <= 1e-9 { 99.0 } else { (allow / *v).min(99.0) };
            }
            Ok(c)
        };
        Ok(match kind {
            "sfm" => sf_material(),
            "sfz" => sf_layer()?,
            "sf" => {
                let mut a = sf_material();
                let b = sf_layer()?;
                for (va, &vb) in a.iter_mut().zip(&b) {
                    *va = va.min(vb);
                }
                a
            }
            _ => {
                let k = FieldKind::parse(kind).ok_or_else(|| err("unknown result field"))?;
                cell_field(grid, &sol.u, self.settings.e0, self.settings.nu, eps, k)
            }
        })
    }

    /// Stress/strain scalar per soup vertex, from the current solution.
    /// Kinds: "vm" | "sxx" | "syy" | "szz" | "sxy" | "syz" | "szx" (MPa),
    /// "evm" | "exx" | "eyy" | "ezz" | "gxy" | "gyz" | "gzx" (strain), and
    /// "sf" — safety factor σ_allow/σ_vM, where the allowable of graded
    /// infill scales with the SAME relative factor as its stiffness
    /// (Gibson–Ashby strength tracks stiffness to first order; the skin
    /// carries the full tensile strength). Capped at 99.
    /// Evaluated at cell centers with the eps the solve actually used.
    pub fn result_field(&self, kind: &str) -> Result<Vec<f32>, JsValue> {
        let cells = self.cell_values(kind)?;
        let (grid, _) = self.grid.as_ref().ok_or_else(|| err("no grid"))?;
        Ok(sample_cell_values(&self.mesh.tris, grid, &cells))
    }

    /// Voxel-hull result geometry: the analysis mesh with EXACT nodal
    /// displacements (hull vertices ARE grid nodes — no surface sampling
    /// like the STL view). Returns [positions f32 (9/tri), displacements
    /// f32 (9/tri), edges f32 (6/segment), edge displacements f32].
    pub fn voxel_results(&self) -> Result<js_sys::Array, JsValue> {
        let sol =
            self.solution.as_ref().ok_or_else(|| err("no solution — run Solve or Optimize"))?;
        let (grid, _) = self.grid.as_ref().ok_or_else(|| err("no grid"))?;
        let (tris, edges) = grid.surface_mesh();
        let tri_disp = node_displacements(&tris, grid, sol);
        let edge_disp = node_displacements(&edges, grid, sol);
        Ok(js_sys::Array::of4(
            &js_sys::Float32Array::from(tris.as_slice()),
            &js_sys::Float32Array::from(tri_disp.as_slice()),
            &js_sys::Float32Array::from(edges.as_slice()),
            &js_sys::Float32Array::from(edge_disp.as_slice()),
        ))
    }

    /// Result field on the voxel hull: one value per hull vertex (3 per
    /// triangle), each triangle carrying its OWNING CELL's value — crisp
    /// per-cell coloring instead of the STL view's smoothed sampling.
    /// Kinds as in `result_field`.
    pub fn voxel_result_field(&self, kind: &str) -> Result<Vec<f32>, JsValue> {
        let cells = self.cell_values(kind)?;
        let (grid, _) = self.grid.as_ref().ok_or_else(|| err("no grid"))?;
        let (_tris, _edges, cell_of_tri) = grid.surface_mesh_where(&|_| true);
        let mut out = Vec::with_capacity(cell_of_tri.len() * 3);
        for &ci in &cell_of_tri {
            let v = cells[ci as usize];
            out.extend_from_slice(&[v, v, v]);
        }
        Ok(out)
    }

    /// Project 3MF with part + modifiers for the chosen slicer flavor:
    /// "orca" (default), "bambu", or "prusa". The part mesh is the ORIGINAL
    /// import tessellation (display subdivision stays internal); the part
    /// carries the perimeter count the optimization assumed. Bambu Studio
    /// (>= 2.06) renamed the "rectilinear" pattern value to "zig-zag"
    /// (still displayed as Rectilinear), so the bambu flavor maps it —
    /// otherwise every project load pops a "values replaced" dialog.
    pub fn export_3mf(&self, slicer: &str) -> Result<Vec<u8>, JsValue> {
        let opt = self.opt.as_ref().ok_or_else(|| err("no optimization result — run optimize first"))?;
        let part = weld(&self.mesh_orig);
        let name = if self.name.is_empty() { "part" } else { &self.name };
        let pattern = opt.solid_pattern.as_deref();
        Ok(match slicer {
            "prusa" => sig_core::threemf::export_prusa_3mf(
                name,
                &part,
                &opt.regions,
                opt.base_density,
                opt.perimeters,
                pattern,
            ),
            s => export_orca_3mf(
                name,
                &part,
                &opt.regions,
                opt.base_density,
                opt.perimeters,
                pattern.map(|p| if s == "bambu" && p == "rectilinear" { "zig-zag" } else { p }),
            ),
        })
    }

    /// Voxel mesh for the Mesh view, optionally cut by a plane: cells whose
    /// CENTER satisfies n·c + constant < 0 are dropped entirely, exposing the
    /// interior cells (voxel-true section — skin thickness inspectable)
    /// instead of a planar cut. Returns [positions f32 (9/tri),
    /// skin f32 (3/tri, 1 = within wall_mm of the surface), edges f32].
    pub fn voxel_mesh_cut(
        &mut self,
        cut: bool,
        nx: f64,
        ny: f64,
        nz: f64,
        constant: f64,
        wall_mm: f64,
    ) -> Result<js_sys::Array, JsValue> {
        self.ensure_grid()?;
        let (grid, _) = self.grid.as_ref().unwrap();
        let (skin, _) = sig_core::simp::classify_cells(grid, wall_mm.clamp(0.2, 5.0));
        let skin_set: std::collections::HashSet<u32> = skin.into_iter().collect();
        let (gnx, gny) = (grid.nx, grid.ny);
        let (h, o) = (grid.h, grid.origin);
        let keep = move |ci: usize| -> bool {
            if !cut {
                return true;
            }
            let cx = ci % gnx;
            let cy = (ci / gnx) % gny;
            let cz = ci / (gnx * gny);
            // Match three.js clipping: keep where distance = n·p + c ≥ 0.
            let d = nx * (o[0] + (cx as f64 + 0.5) * h)
                + ny * (o[1] + (cy as f64 + 0.5) * h)
                + nz * (o[2] + (cz as f64 + 0.5) * h)
                + constant;
            d >= 0.0
        };
        let (tris, edges, cell_of_tri) = grid.surface_mesh_where(&keep);
        let mut skin_flag = Vec::with_capacity(cell_of_tri.len() * 3);
        for &c in &cell_of_tri {
            let f = if skin_set.contains(&c) { 1.0f32 } else { 0.0 };
            skin_flag.extend_from_slice(&[f, f, f]);
        }
        Ok(js_sys::Array::of3(
            &js_sys::Float32Array::from(tris.as_slice()),
            &js_sys::Float32Array::from(skin_flag.as_slice()),
            &js_sys::Float32Array::from(edges.as_slice()),
        ))
    }

    /// Exposed-face hull of the analysis voxel grid (triangle soup, xyz f32).
    pub fn voxel_hull(&mut self) -> Result<Vec<f32>, JsValue> {
        self.ensure_grid()?;
        let (grid, _) = self.grid.as_ref().unwrap();
        Ok(grid.surface_mesh().0)
    }

    /// Deduplicated cell-edge segments of the hull (pairs of xyz f32 points).
    pub fn voxel_edges(&mut self) -> Result<Vec<f32>, JsValue> {
        self.ensure_grid()?;
        let (grid, _) = self.grid.as_ref().unwrap();
        Ok(grid.surface_mesh().1)
    }

    /// Zip of one binary STL per modifier region.
    pub fn export_stls(&self) -> Result<Vec<u8>, JsValue> {
        let opt = self.opt.as_ref().ok_or_else(|| err("no optimization result — run optimize first"))?;
        Ok(export_stl_zip(&opt.regions))
    }
}

/// Taubin-smooth copies of the raw regions (0 passes = verbatim copy).
fn smooth_regions(raw: &[RegionMesh], iters: usize) -> Vec<RegionMesh> {
    raw.iter()
        .map(|r| {
            let mut rr = RegionMesh {
                density: r.density,
                positions: r.positions.clone(),
                indices: r.indices.clone(),
            };
            if iters > 0 {
                taubin_smooth(&mut rr.positions, &rr.indices, iters);
            }
            rr
        })
        .collect()
}

/// Sample a per-cell density field at arbitrary points (xyz triples),
/// searching outward for the nearest design cell; skin counts as solid.
fn sample_points_static(
    points: &[f32],
    grid: &VoxelGrid,
    field: &std::collections::HashMap<u32, f64>,
) -> Vec<f32> {
    let (nx, ny, nz) = (grid.nx, grid.ny, grid.nz);
    let h = grid.h;
    let cell_at = |p: [f64; 3]| -> Option<usize> {
        let cx = ((p[0] - grid.origin[0]) / h).floor() as i64;
        let cy = ((p[1] - grid.origin[1]) / h).floor() as i64;
        let cz = ((p[2] - grid.origin[2]) / h).floor() as i64;
        if cx < 0 || cy < 0 || cz < 0 || cx >= nx as i64 || cy >= ny as i64 || cz >= nz as i64 {
            return None;
        }
        Some(((cz as usize) * ny + cy as usize) * nx + cx as usize)
    };
    let mut out = Vec::with_capacity(points.len() / 3);
    for v in points.chunks_exact(3) {
        let p = [v[0] as f64, v[1] as f64, v[2] as f64];
        let mut val = 1.0f64;
        let mut found = false;
        'search: for r in 0..3i64 {
            for dz in -r..=r {
                for dy in -r..=r {
                    for dx in -r..=r {
                        let q = [p[0] + dx as f64 * h, p[1] + dy as f64 * h, p[2] + dz as f64 * h];
                        if let Some(ci) = cell_at(q) {
                            if let Some(&x) = field.get(&(ci as u32)) {
                                val = x;
                                found = true;
                                break 'search;
                            }
                            if !found && grid.scale[ci] > 0.0 {
                                found = true;
                                val = 1.0; // skin
                            }
                        }
                    }
                }
            }
            if found {
                break;
            }
        }
        out.push(val as f32);
    }
    out
}

/// Sample a per-cell scalar (dense Vec over the padded grid; valid where
/// grid.scale > 0) at every soup vertex — nearest solid cell wins.
fn sample_cell_values(tris: &[[f32; 9]], grid: &VoxelGrid, values: &[f32]) -> Vec<f32> {
    let (nx, ny, nz) = (grid.nx, grid.ny, grid.nz);
    let h = grid.h;
    let cell_at = |p: [f64; 3]| -> Option<usize> {
        let cx = ((p[0] - grid.origin[0]) / h).floor() as i64;
        let cy = ((p[1] - grid.origin[1]) / h).floor() as i64;
        let cz = ((p[2] - grid.origin[2]) / h).floor() as i64;
        if cx < 0 || cy < 0 || cz < 0 || cx >= nx as i64 || cy >= ny as i64 || cz >= nz as i64 {
            return None;
        }
        Some(((cz as usize) * ny + cy as usize) * nx + cx as usize)
    };
    let mut out = Vec::with_capacity(tris.len() * 3);
    for t in tris {
        for v in 0..3 {
            let p = [t[3 * v] as f64, t[3 * v + 1] as f64, t[3 * v + 2] as f64];
            let mut val = 0.0f32;
            'search: for r in 0..3i64 {
                for dz in -r..=r {
                    for dy in -r..=r {
                        for dx in -r..=r {
                            let q = [
                                p[0] + dx as f64 * h,
                                p[1] + dy as f64 * h,
                                p[2] + dz as f64 * h,
                            ];
                            if let Some(ci) = cell_at(q) {
                                if grid.scale[ci] > 0.0 {
                                    val = values[ci];
                                    break 'search;
                                }
                            }
                        }
                    }
                }
            }
            out.push(val);
        }
    }
    out
}

/// Nodal displacement for xyz points that lie ON grid nodes (voxel hull
/// vertices and cell-edge endpoints) — exact lookup, no interpolation.
fn node_displacements(points: &[f32], grid: &VoxelGrid, sol: &Solution) -> Vec<f32> {
    let h = grid.h;
    let o = grid.origin;
    let mut out = Vec::with_capacity(points.len());
    for p in points.chunks_exact(3) {
        let x = (((p[0] as f64 - o[0]) / h).round() as usize).min(sol.mx - 1);
        let y = (((p[1] as f64 - o[1]) / h).round() as usize).min(sol.my - 1);
        let z = (((p[2] as f64 - o[2]) / h).round() as usize).min(sol.mz - 1);
        let n = (z * sol.my + y) * sol.mx + x;
        out.extend_from_slice(&sol.u[3 * n..3 * n + 3]);
    }
    out
}

/// Free-function clone of sample_cell_field for use inside the progress
/// closure (no &self available there).
fn sample_field_static(
    tris: &[[f32; 9]],
    grid: &VoxelGrid,
    field: &std::collections::HashMap<u32, f64>,
) -> Vec<f32> {
    let (nx, ny, nz) = (grid.nx, grid.ny, grid.nz);
    let h = grid.h;
    let cell_at = |p: [f64; 3]| -> Option<usize> {
        let cx = ((p[0] - grid.origin[0]) / h).floor() as i64;
        let cy = ((p[1] - grid.origin[1]) / h).floor() as i64;
        let cz = ((p[2] - grid.origin[2]) / h).floor() as i64;
        if cx < 0 || cy < 0 || cz < 0 || cx >= nx as i64 || cy >= ny as i64 || cz >= nz as i64 {
            return None;
        }
        Some(((cz as usize) * ny + cy as usize) * nx + cx as usize)
    };
    let mut out = Vec::with_capacity(tris.len() * 3);
    for t in tris {
        for v in 0..3 {
            let p = [t[3 * v] as f64, t[3 * v + 1] as f64, t[3 * v + 2] as f64];
            let mut val = 1.0f64;
            let mut found = false;
            'search: for r in 0..3i64 {
                for dz in -r..=r {
                    for dy in -r..=r {
                        for dx in -r..=r {
                            let q =
                                [p[0] + dx as f64 * h, p[1] + dy as f64 * h, p[2] + dz as f64 * h];
                            if let Some(ci) = cell_at(q) {
                                if let Some(&x) = field.get(&(ci as u32)) {
                                    val = x;
                                    found = true;
                                    break 'search;
                                }
                                if !found && grid.scale[ci] > 0.0 {
                                    found = true;
                                    val = 1.0;
                                }
                            }
                        }
                    }
                }
                if found {
                    break;
                }
            }
            out.push(val as f32);
        }
    }
    out
}

// ---- Phase-1 raw benchmark exports (used by wasm-bench.js via raw cargo build) ----

use sig_core::mesh::primitives;
use sig_core::{solve_static, BoxRegion, StaticProblem};

#[no_mangle]
pub extern "C" fn bench_voxelize(h: f64) -> u32 {
    let sph = primitives::sphere([0.0; 3], 25.0, 128, 64);
    let grid = VoxelGrid::voxelize(&sph, h);
    grid.solid_count() as u32
}

#[no_mangle]
pub extern "C" fn bench_solve(nx: u32, ny: u32, nz: u32, h: f64) -> f64 {
    let (nx, ny, nz) = (nx as usize, ny as usize, nz as usize);
    let (e0, nu, f) = (2000.0f64, 0.3f64, -10.0f64);
    let (l, bdim, hdim) = (nx as f64 * h, ny as f64 * h, nz as f64 * h);
    let grid = VoxelGrid::solid_box(nx, ny, nz, h);
    let problem = StaticProblem {
        grid,
        fixed: vec![BoxRegion::new([-0.1, -1.0, -1.0], [0.1, bdim + 1.0, hdim + 1.0])],
        loads: vec![(
            BoxRegion::new([l - 0.1 * h, -1.0, -1.0], [l + h, bdim + 1.0, hdim + 1.0]),
            [0.0, 0.0, f],
        )],
        settings: SolveSettings { e0, nu, tol: 1e-5, max_iter: 300, ..Default::default() },
    };
    let sol = match solve_static(&problem) {
        Ok(s) => s,
        Err(_) => return -1.0,
    };
    let tip = match sol.mean_displacement(&BoxRegion::new(
        [l - 0.1 * h, -1.0, -1.0],
        [l + h, bdim + 1.0, hdim + 1.0],
    )) {
        Some(t) => t,
        None => return -2.0,
    };
    let inertia = bdim * hdim.powi(3) / 12.0;
    let area = bdim * hdim;
    let g = e0 / (2.0 * (1.0 + nu));
    let kappa = 10.0 * (1.0 + nu) / (12.0 + 11.0 * nu);
    let exact = f * l.powi(3) / (3.0 * e0 * inertia) + f * l / (kappa * g * area);
    tip[2] / exact
}
