//! WASM API for the Smart Infill Generator web app.
//!
//! One `Model` instance lives in a web worker and owns mesh, segmentation,
//! voxel grid, boundary conditions, and the last solution. Bulk data crosses
//! the boundary as typed arrays; small results as JSON strings.

use sig_core::attach::{assemble, check_problem, BcKind, BcSpec};
use sig_core::bins::{
    assign_bins, cleanup_small_regions, cluster_densities, extract_iso, extract_region,
    taubin_smooth, RegionMesh,
};
use sig_core::mesh::TriMesh;
use sig_core::segment::{segment, Segmentation};
use sig_core::simp::{evaluate, optimize as simp_optimize, OptimizeParams};
use sig_core::solve::{active_nodes, pad_for_levels, solve_nodes, SolveSettings, Solution};
use sig_core::threemf::{export_orca_3mf, export_stl_zip, import_3mf, weld};
use sig_core::voxel::VoxelGrid;
use wasm_bindgen::prelude::*;

const GRAVITY_MM_S2: [f64; 3] = [0.0, 0.0, -9810.0];

struct OptOutput {
    /// Smoothed regions (display + export); regenerated by resmooth_regions.
    regions: Vec<RegionMesh>,
    /// Raw marching-tets regions before smoothing (re-smoothing source).
    regions_raw: Vec<RegionMesh>,
    base_density: f64,
    /// Final per-design-cell binned density.
    cell_density: std::collections::HashMap<u32, f64>,
    /// Continuous (pre-binning) field for the density-threshold isosurface.
    design_cells: Vec<u32>,
    x_cont: Vec<f64>,
    summary: String,
}

#[wasm_bindgen]
pub struct Model {
    /// Working mesh: display + segmentation + BC attachment + voxelization.
    /// Subdivided at load so deformed shapes can actually bend (a coarse STL
    /// face has no vertices to carry the curve).
    mesh: TriMesh,
    /// Original tessellation as imported — exported 3MFs carry this one.
    mesh_orig: TriMesh,
    /// Original-triangle index per working-mesh triangle. Segmentation runs
    /// on the original mesh and is mapped through this: subdivision creates
    /// T-junctions along shared edges (neighbors get different n), so
    /// segmenting the subdivided soup would fragment flat surfaces.
    parents: Vec<u32>,
    name: String,
    mesh_objects: usize,
    seg: Segmentation,
    bcs: Vec<BcSpec>,
    settings: SolveSettings,
    /// tonne/mm³
    density: f64,
    gravity_on: bool,
    target_cells: u32,
    grid: Option<(VoxelGrid, usize)>, // padded grid + level count
    solution: Option<Solution>,
    opt: Option<OptOutput>,
}

fn err(e: impl std::fmt::Display) -> JsValue {
    JsValue::from_str(&e.to_string())
}

/// Patch ids computed on the original mesh, carried onto the subdivided
/// working mesh (each child inherits its parent triangle's patch).
fn remap_segmentation(orig: &Segmentation, parents: &[u32]) -> Segmentation {
    Segmentation {
        patch_of_tri: parents.iter().map(|&p| orig.patch_of_tri[p as usize]).collect(),
        patch_count: orig.patch_count,
    }
}

#[wasm_bindgen]
impl Model {
    /// Parse STL (binary/ASCII) or 3MF (detected by zip magic); segment at 30°.
    #[wasm_bindgen(constructor)]
    pub fn new(bytes: &[u8], name: &str) -> Result<Model, JsValue> {
        let (mesh_orig, mesh_objects) = if bytes.len() >= 2 && &bytes[..2] == b"PK" {
            import_3mf(bytes).map_err(err)?
        } else {
            (TriMesh::from_stl(bytes).map_err(err)?, 1)
        };
        // Refine the display/analysis tessellation: edges capped at ~1/60 of
        // the diagonal so deflection curves are visible on coarse STLs.
        // Dense meshes pass through unchanged (160k-triangle budget).
        let (mesh, parents) = match mesh_orig.bounds() {
            Some((lo, hi)) => {
                let diag = ((hi[0] - lo[0]).powi(2)
                    + (hi[1] - lo[1]).powi(2)
                    + (hi[2] - lo[2]).powi(2))
                .sqrt();
                mesh_orig.subdivided_with_parents(diag / 60.0, 160_000)
            }
            None => (mesh_orig.clone(), (0..mesh_orig.len() as u32).collect()),
        };
        let seg = remap_segmentation(&segment(&mesh_orig, 30.0), &parents);
        Ok(Model {
            mesh,
            mesh_orig,
            parents,
            name: name.to_string(),
            mesh_objects,
            seg,
            bcs: Vec::new(),
            settings: SolveSettings::default(),
            density: 1.24e-9, // PLA
            gravity_on: false,
            target_cells: 300_000,
            grid: None,
            solution: None,
            opt: None,
        })
    }

    /// Number of mesh objects found in the imported file (UI warns when >1).
    pub fn mesh_object_count(&self) -> u32 {
        self.mesh_objects as u32
    }

    pub fn triangle_count(&self) -> u32 {
        self.mesh.len() as u32
    }

    /// Triangle soup positions, 9 floats per triangle (three.js non-indexed).
    pub fn positions(&self) -> Vec<f32> {
        let mut out = Vec::with_capacity(self.mesh.tris.len() * 9);
        for t in &self.mesh.tris {
            out.extend_from_slice(t);
        }
        out
    }

    /// Patch id per triangle.
    pub fn patch_ids(&self) -> Vec<u32> {
        self.seg.patch_of_tri.clone()
    }

    pub fn patch_count(&self) -> u32 {
        self.seg.patch_count as u32
    }

    /// Re-run segmentation with a different crease angle (degrees).
    pub fn resegment(&mut self, angle_deg: f64) {
        self.seg =
            remap_segmentation(&segment(&self.mesh_orig, angle_deg.clamp(1.0, 89.0)), &self.parents);
    }

    /// [lox, loy, loz, hix, hiy, hiz] in mm.
    pub fn bbox(&self) -> Vec<f64> {
        match self.mesh.bounds() {
            Some((lo, hi)) => vec![lo[0], lo[1], lo[2], hi[0], hi[1], hi[2]],
            None => vec![0.0; 6],
        }
    }

    /// e0 in MPa, density in g/cm³.
    pub fn set_material(&mut self, e0: f64, nu: f64, density_g_cm3: f64) {
        self.settings.e0 = e0;
        self.settings.nu = nu;
        self.density = density_g_cm3 * 1e-9;
        self.solution = None;
        self.opt = None;
    }

    pub fn set_gravity(&mut self, on: bool) {
        self.gravity_on = on;
        self.solution = None;
        self.opt = None;
    }

    pub fn set_resolution(&mut self, target_cells: u32) {
        if target_cells != self.target_cells {
            self.target_cells = target_cells.clamp(10_000, 4_000_000);
            self.grid = None;
            self.solution = None;
        self.opt = None;
        }
    }

    pub fn clear_bcs(&mut self) {
        self.bcs.clear();
        self.solution = None;
        self.opt = None;
    }

    pub fn add_fixed(&mut self, tris: &[u32]) {
        self.bcs.push(BcSpec { kind: BcKind::Fixed, tris: tris.to_vec() });
        self.solution = None;
        self.opt = None;
    }

    pub fn add_frictionless(&mut self, tris: &[u32]) {
        self.bcs.push(BcSpec { kind: BcKind::Frictionless, tris: tris.to_vec() });
        self.solution = None;
        self.opt = None;
    }

    pub fn add_force(&mut self, tris: &[u32], fx: f64, fy: f64, fz: f64) {
        self.bcs.push(BcSpec { kind: BcKind::Force([fx, fy, fz]), tris: tris.to_vec() });
        self.solution = None;
        self.opt = None;
    }

    pub fn add_pressure(&mut self, tris: &[u32], mpa: f64) {
        self.bcs.push(BcSpec { kind: BcKind::Pressure(mpa), tris: tris.to_vec() });
        self.solution = None;
        self.opt = None;
    }

    fn ensure_grid(&mut self) -> Result<(), JsValue> {
        if self.grid.is_some() {
            return Ok(());
        }
        let (lo, hi) = self.mesh.bounds().ok_or_else(|| err("empty mesh"))?;
        let vol = (hi[0] - lo[0]).max(1e-6) * (hi[1] - lo[1]).max(1e-6) * (hi[2] - lo[2]).max(1e-6);
        let h = (vol / self.target_cells as f64).cbrt().max(1e-3);
        let grid = VoxelGrid::voxelize(&self.mesh, h);
        if grid.solid_count() == 0 {
            return Err(err("voxelization produced no solid cells — model too thin for this resolution"));
        }
        let (padded, levels) = pad_for_levels(&grid, self.settings.max_levels);
        self.grid = Some((padded, levels));
        Ok(())
    }

    /// JSON: { nx, ny, nz, h, cells, solid }
    pub fn voxel_info(&mut self) -> Result<String, JsValue> {
        self.ensure_grid()?;
        let (g, _) = self.grid.as_ref().unwrap();
        Ok(serde_json::json!({
            "nx": g.nx, "ny": g.ny, "nz": g.nz, "h": g.h,
            "cells": g.cell_count(), "solid": g.solid_count(),
        })
        .to_string())
    }

    fn gravity_arg(&self) -> Option<([f64; 3], f64)> {
        if self.gravity_on {
            Some((GRAVITY_MM_S2, self.density))
        } else {
            None
        }
    }

    /// Island + rigid-body-mode check. JSON CheckReport.
    pub fn check(&mut self) -> Result<String, JsValue> {
        self.ensure_grid()?;
        let (grid, _) = self.grid.as_ref().unwrap();
        let asm = assemble(&self.mesh, grid, &self.bcs, self.gravity_arg(), &self.settings)
            .map_err(err)?;
        let report = check_problem(grid, &asm);
        let comps: Vec<serde_json::Value> = report
            .components
            .iter()
            .map(|c| {
                serde_json::json!({
                    "cells": c.cells,
                    "constrained": c.constrained,
                    "lambdaRatio": c.lambda_ratio,
                    "hasLoads": c.has_loads,
                    "mode": c.mode.as_ref().map(|m| serde_json::json!({
                        "t": m.t, "r": m.r, "center": m.center,
                    })),
                })
            })
            .collect();
        Ok(serde_json::json!({
            "ok": report.ok,
            "islandCount": report.island_count,
            "components": comps,
        })
        .to_string())
    }

    /// Run the static solve. JSON: { iterations, relResidual, maxDisplacement }.
    pub fn solve(&mut self) -> Result<String, JsValue> {
        self.ensure_grid()?;
        let (grid, levels) = self.grid.as_ref().unwrap();
        let asm = assemble(&self.mesh, grid, &self.bcs, self.gravity_arg(), &self.settings)
            .map_err(err)?;
        let report = check_problem(grid, &asm);
        if !report.ok {
            return Err(err("model is under-constrained — run check() for details"));
        }
        let sol = solve_nodes(grid, *levels, &asm.problem, &self.settings).map_err(err)?;
        let out = serde_json::json!({
            "iterations": sol.iterations,
            "relResidual": sol.rel_residual,
            "maxDisplacement": sol.max_displacement(),
        })
        .to_string();
        self.solution = Some(sol);
        Ok(out)
    }

    /// Displacement vector (mm) per soup vertex: 9 floats per triangle.
    pub fn vertex_displacements(&self) -> Result<Vec<f32>, JsValue> {
        let sol = self.solution.as_ref().ok_or_else(|| err("no solution — call solve() first"))?;
        let mut out = Vec::with_capacity(self.mesh.tris.len() * 9);
        for t in &self.mesh.tris {
            for v in 0..3 {
                let p = [t[3 * v] as f64, t[3 * v + 1] as f64, t[3 * v + 2] as f64];
                let u = sol.sample_displacement(p);
                out.extend_from_slice(&[u[0] as f32, u[1] as f32, u[2] as f32]);
            }
        }
        Ok(out)
    }

    /// Sample a density field (cell -> density map) at every soup vertex,
    /// probing slightly inward and falling back to nearby solid cells.
    fn sample_cell_field(&self, grid: &VoxelGrid, field: &std::collections::HashMap<u32, f64>) -> Vec<f32> {
        let (nx, ny, nz) = (grid.nx, grid.ny, grid.nz);
        let h = grid.h;
        let cell_at = |p: [f64; 3]| -> Option<usize> {
            let cx = ((p[0] - grid.origin[0]) / h).floor() as i64;
            let cy = ((p[1] - grid.origin[1]) / h).floor() as i64;
            let cz = ((p[2] - grid.origin[2]) / h).floor() as i64;
            if cx < 0 || cy < 0 || cz < 0 || cx >= nx as i64 || cy >= ny as i64 || cz >= nz as i64 {
                return None;
            }
            Some(((cz as usize) * ny + cy as usize) * nx + cx as usize)
        };
        let mut out = Vec::with_capacity(self.mesh.tris.len() * 3);
        for t in &self.mesh.tris {
            for v in 0..3 {
                let p = [t[3 * v] as f64, t[3 * v + 1] as f64, t[3 * v + 2] as f64];
                // Search a small neighborhood: prefer a design cell, else skin.
                let mut val = 1.0f64;
                let mut found = false;
                'search: for r in 0..3i64 {
                    for dz in -r..=r {
                        for dy in -r..=r {
                            for dx in -r..=r {
                                let q = [
                                    p[0] + dx as f64 * h,
                                    p[1] + dy as f64 * h,
                                    p[2] + dz as f64 * h,
                                ];
                                if let Some(ci) = cell_at(q) {
                                    if let Some(&x) = field.get(&(ci as u32)) {
                                        val = x;
                                        found = true;
                                        break 'search;
                                    }
                                    if !found && grid.scale[ci] > 0.0 {
                                        found = true;
                                        val = 1.0; // skin
                                    }
                                }
                            }
                        }
                    }
                    if found {
                        break;
                    }
                }
                out.push(val as f32);
            }
        }
        out
    }

    /// Run the density optimization + binning + verification. Progress gets
    /// called per iteration with (jsonString, Float32Array vertexDensity,
    /// Float32Array skeletonPositions, Uint32Array skeletonIndices) — the
    /// skeleton is the evolving isosurface of cells denser than 40%.
    /// Infill law E/E0 = coeff * rho^exponent; skin thickness is
    /// perimeters * line_width (analysis only — the 3MF never pins walls).
    /// `smooth_iters` = Taubin passes applied to the exported regions.
    #[allow(clippy::too_many_arguments)]
    pub fn optimize(
        &mut self,
        budget_pct: f64,
        exponent: f64,
        coeff: f64,
        perimeters: u32,
        line_width: f64,
        smooth_iters: u32,
        n_bins: u32,
        progress: &js_sys::Function,
    ) -> Result<String, JsValue> {
        self.ensure_grid()?;
        let exponent = exponent.clamp(1.0, 3.5);
        let coeff = coeff.clamp(0.05, 2.0);
        let perimeters = perimeters.clamp(1, 8);
        let wall_mm = perimeters as f64 * line_width.clamp(0.1, 1.5);
        let smooth_iters = (smooth_iters as usize).min(60);
        let n_bins = (n_bins as usize).clamp(2, 4);

        // Assemble + check before burning time.
        let (grid, levels) = self.grid.as_ref().unwrap();
        let asm = assemble(&self.mesh, grid, &self.bcs, self.gravity_arg(), &self.settings)
            .map_err(err)?;
        let report = check_problem(grid, &asm);
        if !report.ok {
            return Err(err("model is under-constrained — fix the setup first (run Check)"));
        }

        let params = OptimizeParams {
            budget: (budget_pct / 100.0).clamp(0.05, 1.0),
            exponent,
            coeff,
            wall_mm: wall_mm.clamp(0.2, 5.0),
            // Cap is a safety net; the change-based convergence criterion
            // normally stops the loop earlier.
            max_iter: 40,
            ..Default::default()
        };

        let mesh = &self.mesh;
        let max_iter = params.max_iter;
        // Borrow self fields disjointly for the progress closure.
        let tris = &mesh.tris;
        // Isosurface threshold for the live "shape emerging" view.
        const SKEL_DENSITY: f64 = 0.4;
        let result = simp_optimize(
            grid,
            *levels,
            &asm.problem,
            &self.settings,
            &params,
            |p, x_phys, design_cells| {
                let mut field: std::collections::HashMap<u32, f64> =
                    std::collections::HashMap::with_capacity(design_cells.len());
                for (k, &c) in design_cells.iter().enumerate() {
                    field.insert(c, x_phys[k]);
                }
                // Inline vertex sampling (cannot call &self methods here).
                let vd = sample_field_static(tris, grid, &field);
                // Evolving dense-core isosurface so the user watches the
                // optimized shape gain detail iteration by iteration. Built
                // on the CONTINUOUS filtered field — the level set is smooth;
                // a binary per-cell indicator grows tent spikes wherever a
                // single cell crosses the threshold.
                let value = |ci: usize| field.get(&(ci as u32)).copied().unwrap_or(0.0);
                let mut skel = extract_iso(grid, &value, SKEL_DENSITY);
                taubin_smooth(&mut skel.positions, &skel.indices, 3);
                let skel_density = sample_points_static(&skel.positions, grid, &field);
                let json = serde_json::json!({
                    "iteration": p.iteration,
                    "maxIter": max_iter,
                    "compliance": p.compliance,
                    "massFrac": p.mass_frac,
                    "change": p.change,
                    "meanChange": p.mean_change,
                })
                .to_string();
                let args = js_sys::Array::of5(
                    &JsValue::from_str(&json),
                    &js_sys::Float32Array::from(vd.as_slice()),
                    &js_sys::Float32Array::from(skel.positions.as_slice()),
                    &js_sys::Uint32Array::from(skel.indices.as_slice()),
                    &js_sys::Float32Array::from(skel_density.as_slice()),
                );
                let _ = progress.apply(&JsValue::NULL, &args);
            },
        )
        .map_err(err)?;

        // ---- bins ----
        let centers = cluster_densities(&result.x, n_bins);
        let mut bins = assign_bins(&result.x, &centers);
        let min_cells = (result.design_cells.len() / 500).max(30);
        cleanup_small_regions(grid, &result.design_cells, &mut bins, centers.len(), min_cells);
        let x_binned: Vec<f64> = bins.iter().map(|&b| centers[b as usize]).collect();

        // ---- verification + baselines ----
        let (c_binned, _maxd, u_binned) = evaluate(
            grid, *levels, &asm.problem, &self.settings, &result.skin_cells,
            &result.design_cells, &x_binned, exponent, coeff, Some(&result.u),
        )
        .map_err(err)?;
        let mean_binned = x_binned.iter().sum::<f64>() / x_binned.len().max(1) as f64;
        let x_uniform = vec![mean_binned; x_binned.len()];
        let (c_uniform, _, _) = evaluate(
            grid, *levels, &asm.problem, &self.settings, &result.skin_cells,
            &result.design_cells, &x_uniform, exponent, coeff, Some(&result.u),
        )
        .map_err(err)?;
        let x_solid = vec![1.0; x_binned.len()];
        let (c_solid, _, _) = evaluate(
            grid, *levels, &asm.problem, &self.settings, &result.skin_cells,
            &result.design_cells, &x_solid, exponent, coeff, Some(&result.u),
        )
        .map_err(err)?;

        // Solution object for the deformed view.
        let (mx, my, mz) = (grid.nx + 1, grid.ny + 1, grid.nz + 1);
        let mut max_disp = 0f64;
        for n in 0..mx * my * mz {
            let m = u_binned[3 * n] * u_binned[3 * n]
                + u_binned[3 * n + 1] * u_binned[3 * n + 1]
                + u_binned[3 * n + 2] * u_binned[3 * n + 2];
            max_disp = max_disp.max(m);
        }
        max_disp = max_disp.sqrt();
        self.solution = Some(Solution {
            u: u_binned.iter().map(|&v| v as f32).collect(),
            mx,
            my,
            mz,
            h: grid.h,
            origin: grid.origin,
            active: active_nodes(grid),
            iterations: result.iterations,
            rel_residual: 0.0,
        });

        // ---- regions (bins above base) ----
        let mut bin_of_cell: std::collections::HashMap<u32, u8> = Default::default();
        for (i, &c) in result.design_cells.iter().enumerate() {
            bin_of_cell.insert(c, bins[i]);
        }
        let mut regions_raw = Vec::new();
        for level in 1..centers.len() {
            let inside = |ci: usize| -> bool {
                bin_of_cell.get(&(ci as u32)).map_or(false, |&b| b as usize >= level)
            };
            let mut r = extract_region(grid, &inside, 0.4);
            if r.indices.is_empty() {
                continue;
            }
            r.density = centers[level];
            regions_raw.push(r);
        }
        let regions = smooth_regions(&regions_raw, smooth_iters);

        // ---- mass + summary ----
        let cell_vol = grid.h * grid.h * grid.h;
        let n_skin = result.skin_cells.len() as f64;
        let n_solid = n_skin + result.design_cells.len() as f64;
        let grams = |interior: f64| (n_skin + interior) * cell_vol * self.density * 1e6;
        let mass_part = grams(x_binned.iter().sum::<f64>());
        let mass_solid = grams(result.design_cells.len() as f64);
        let mass_frac = (n_skin + x_binned.iter().sum::<f64>()) / n_solid;

        let bin_counts: Vec<usize> =
            (0..centers.len()).map(|c| bins.iter().filter(|&&b| b as usize == c).count()).collect();
        let summary = serde_json::json!({
            "iterations": result.iterations,
            "converged": result.converged,
            "bins": centers.iter().zip(&bin_counts).map(|(&d, &n)| serde_json::json!({
                "density": d, "cells": n,
            })).collect::<Vec<_>>(),
            "baseDensity": centers[0],
            "regionCount": regions.len(),
            "massGrams": mass_part,
            "massSolidGrams": mass_solid,
            "massFrac": mass_frac,
            "effectiveBudget": result.effective_budget,
            "stiffnessVsSolid": c_solid / c_binned,
            "gainVsUniform": c_uniform / c_binned - 1.0,
            "maxDisplacement": max_disp,
        })
        .to_string();

        let mut field: std::collections::HashMap<u32, f64> = Default::default();
        for (i, &c) in result.design_cells.iter().enumerate() {
            field.insert(c, x_binned[i]);
        }
        self.opt = Some(OptOutput {
            regions,
            regions_raw,
            base_density: centers[0],
            cell_density: field,
            design_cells: result.design_cells,
            x_cont: result.x,
            summary: summary.clone(),
        });
        Ok(summary)
    }

    /// Re-apply Taubin smoothing to the extracted regions (live preview of
    /// the smoothing slider). Affects display AND subsequent exports.
    pub fn resmooth_regions(&mut self, iters: u32) -> Result<(), JsValue> {
        let opt = self.opt.as_mut().ok_or_else(|| err("no optimization result"))?;
        opt.regions = smooth_regions(&opt.regions_raw, (iters as usize).min(60));
        Ok(())
    }

    /// Isosurface of the final continuous density field at `threshold`
    /// (0..1): everything denser than the threshold. Returns
    /// [positions f32, indices u32, per-vertex density f32] for the
    /// cutaway view (colored with the density legend ramp).
    pub fn density_isosurface(&self, threshold: f64) -> Result<js_sys::Array, JsValue> {
        let opt = self.opt.as_ref().ok_or_else(|| err("no optimization result"))?;
        let (grid, _) = self.grid.as_ref().ok_or_else(|| err("no grid"))?;
        let mut field: std::collections::HashMap<u32, f64> =
            std::collections::HashMap::with_capacity(opt.design_cells.len());
        for (i, &c) in opt.design_cells.iter().enumerate() {
            field.insert(c, opt.x_cont[i]);
        }
        let t = threshold.clamp(0.0, 1.0);
        // Continuous level set of the filtered field — smooth by nature.
        let value = |ci: usize| field.get(&(ci as u32)).copied().unwrap_or(0.0);
        let mut r = extract_iso(grid, &value, t);
        taubin_smooth(&mut r.positions, &r.indices, 3);
        let density = sample_points_static(&r.positions, grid, &field);
        Ok(js_sys::Array::of3(
            &js_sys::Float32Array::from(r.positions.as_slice()),
            &js_sys::Uint32Array::from(r.indices.as_slice()),
            &js_sys::Float32Array::from(density.as_slice()),
        ))
    }

    pub fn region_count(&self) -> u32 {
        self.opt.as_ref().map_or(0, |o| o.regions.len() as u32)
    }

    pub fn region_density(&self, i: u32) -> f64 {
        self.opt.as_ref().and_then(|o| o.regions.get(i as usize)).map_or(0.0, |r| r.density)
    }

    pub fn region_positions(&self, i: u32) -> Vec<f32> {
        self.opt
            .as_ref()
            .and_then(|o| o.regions.get(i as usize))
            .map_or(Vec::new(), |r| r.positions.clone())
    }

    pub fn region_indices(&self, i: u32) -> Vec<u32> {
        self.opt
            .as_ref()
            .and_then(|o| o.regions.get(i as usize))
            .map_or(Vec::new(), |r| r.indices.clone())
    }

    /// Final binned density per soup vertex (density view).
    pub fn vertex_density(&self) -> Result<Vec<f32>, JsValue> {
        let opt = self.opt.as_ref().ok_or_else(|| err("no optimization result"))?;
        let (grid, _) = self.grid.as_ref().ok_or_else(|| err("no grid"))?;
        Ok(self.sample_cell_field(grid, &opt.cell_density))
    }

    /// Orca/Bambu project 3MF with part + nested modifiers. The part mesh is
    /// the ORIGINAL import tessellation (display subdivision stays internal).
    pub fn export_3mf(&self) -> Result<Vec<u8>, JsValue> {
        let opt = self.opt.as_ref().ok_or_else(|| err("no optimization result — run optimize first"))?;
        let part = weld(&self.mesh_orig);
        let name = if self.name.is_empty() { "part" } else { &self.name };
        Ok(export_orca_3mf(name, &part, &opt.regions, opt.base_density))
    }

    /// Exposed-face hull of the analysis voxel grid (triangle soup, xyz f32).
    pub fn voxel_hull(&mut self) -> Result<Vec<f32>, JsValue> {
        self.ensure_grid()?;
        let (grid, _) = self.grid.as_ref().unwrap();
        Ok(grid.surface_mesh().0)
    }

    /// Deduplicated cell-edge segments of the hull (pairs of xyz f32 points).
    pub fn voxel_edges(&mut self) -> Result<Vec<f32>, JsValue> {
        self.ensure_grid()?;
        let (grid, _) = self.grid.as_ref().unwrap();
        Ok(grid.surface_mesh().1)
    }

    /// Zip of one binary STL per modifier region.
    pub fn export_stls(&self) -> Result<Vec<u8>, JsValue> {
        let opt = self.opt.as_ref().ok_or_else(|| err("no optimization result — run optimize first"))?;
        Ok(export_stl_zip(&opt.regions))
    }
}

/// Taubin-smooth copies of the raw regions (0 passes = verbatim copy).
fn smooth_regions(raw: &[RegionMesh], iters: usize) -> Vec<RegionMesh> {
    raw.iter()
        .map(|r| {
            let mut rr = RegionMesh {
                density: r.density,
                positions: r.positions.clone(),
                indices: r.indices.clone(),
            };
            if iters > 0 {
                taubin_smooth(&mut rr.positions, &rr.indices, iters);
            }
            rr
        })
        .collect()
}

/// Sample a per-cell density field at arbitrary points (xyz triples),
/// searching outward for the nearest design cell; skin counts as solid.
fn sample_points_static(
    points: &[f32],
    grid: &VoxelGrid,
    field: &std::collections::HashMap<u32, f64>,
) -> Vec<f32> {
    let (nx, ny, nz) = (grid.nx, grid.ny, grid.nz);
    let h = grid.h;
    let cell_at = |p: [f64; 3]| -> Option<usize> {
        let cx = ((p[0] - grid.origin[0]) / h).floor() as i64;
        let cy = ((p[1] - grid.origin[1]) / h).floor() as i64;
        let cz = ((p[2] - grid.origin[2]) / h).floor() as i64;
        if cx < 0 || cy < 0 || cz < 0 || cx >= nx as i64 || cy >= ny as i64 || cz >= nz as i64 {
            return None;
        }
        Some(((cz as usize) * ny + cy as usize) * nx + cx as usize)
    };
    let mut out = Vec::with_capacity(points.len() / 3);
    for v in points.chunks_exact(3) {
        let p = [v[0] as f64, v[1] as f64, v[2] as f64];
        let mut val = 1.0f64;
        let mut found = false;
        'search: for r in 0..3i64 {
            for dz in -r..=r {
                for dy in -r..=r {
                    for dx in -r..=r {
                        let q = [p[0] + dx as f64 * h, p[1] + dy as f64 * h, p[2] + dz as f64 * h];
                        if let Some(ci) = cell_at(q) {
                            if let Some(&x) = field.get(&(ci as u32)) {
                                val = x;
                                found = true;
                                break 'search;
                            }
                            if !found && grid.scale[ci] > 0.0 {
                                found = true;
                                val = 1.0; // skin
                            }
                        }
                    }
                }
            }
            if found {
                break;
            }
        }
        out.push(val as f32);
    }
    out
}

/// Free-function clone of sample_cell_field for use inside the progress
/// closure (no &self available there).
fn sample_field_static(
    tris: &[[f32; 9]],
    grid: &VoxelGrid,
    field: &std::collections::HashMap<u32, f64>,
) -> Vec<f32> {
    let (nx, ny, nz) = (grid.nx, grid.ny, grid.nz);
    let h = grid.h;
    let cell_at = |p: [f64; 3]| -> Option<usize> {
        let cx = ((p[0] - grid.origin[0]) / h).floor() as i64;
        let cy = ((p[1] - grid.origin[1]) / h).floor() as i64;
        let cz = ((p[2] - grid.origin[2]) / h).floor() as i64;
        if cx < 0 || cy < 0 || cz < 0 || cx >= nx as i64 || cy >= ny as i64 || cz >= nz as i64 {
            return None;
        }
        Some(((cz as usize) * ny + cy as usize) * nx + cx as usize)
    };
    let mut out = Vec::with_capacity(tris.len() * 3);
    for t in tris {
        for v in 0..3 {
            let p = [t[3 * v] as f64, t[3 * v + 1] as f64, t[3 * v + 2] as f64];
            let mut val = 1.0f64;
            let mut found = false;
            'search: for r in 0..3i64 {
                for dz in -r..=r {
                    for dy in -r..=r {
                        for dx in -r..=r {
                            let q =
                                [p[0] + dx as f64 * h, p[1] + dy as f64 * h, p[2] + dz as f64 * h];
                            if let Some(ci) = cell_at(q) {
                                if let Some(&x) = field.get(&(ci as u32)) {
                                    val = x;
                                    found = true;
                                    break 'search;
                                }
                                if !found && grid.scale[ci] > 0.0 {
                                    found = true;
                                    val = 1.0;
                                }
                            }
                        }
                    }
                }
                if found {
                    break;
                }
            }
            out.push(val as f32);
        }
    }
    out
}

// ---- Phase-1 raw benchmark exports (used by wasm-bench.js via raw cargo build) ----

use sig_core::mesh::primitives;
use sig_core::{solve_static, BoxRegion, StaticProblem};

#[no_mangle]
pub extern "C" fn bench_voxelize(h: f64) -> u32 {
    let sph = primitives::sphere([0.0; 3], 25.0, 128, 64);
    let grid = VoxelGrid::voxelize(&sph, h);
    grid.solid_count() as u32
}

#[no_mangle]
pub extern "C" fn bench_solve(nx: u32, ny: u32, nz: u32, h: f64) -> f64 {
    let (nx, ny, nz) = (nx as usize, ny as usize, nz as usize);
    let (e0, nu, f) = (2000.0f64, 0.3f64, -10.0f64);
    let (l, bdim, hdim) = (nx as f64 * h, ny as f64 * h, nz as f64 * h);
    let grid = VoxelGrid::solid_box(nx, ny, nz, h);
    let problem = StaticProblem {
        grid,
        fixed: vec![BoxRegion::new([-0.1, -1.0, -1.0], [0.1, bdim + 1.0, hdim + 1.0])],
        loads: vec![(
            BoxRegion::new([l - 0.1 * h, -1.0, -1.0], [l + h, bdim + 1.0, hdim + 1.0]),
            [0.0, 0.0, f],
        )],
        settings: SolveSettings { e0, nu, tol: 1e-5, max_iter: 300, ..Default::default() },
    };
    let sol = match solve_static(&problem) {
        Ok(s) => s,
        Err(_) => return -1.0,
    };
    let tip = match sol.mean_displacement(&BoxRegion::new(
        [l - 0.1 * h, -1.0, -1.0],
        [l + h, bdim + 1.0, hdim + 1.0],
    )) {
        Some(t) => t,
        None => return -2.0,
    };
    let inertia = bdim * hdim.powi(3) / 12.0;
    let area = bdim * hdim;
    let g = e0 / (2.0 * (1.0 + nu));
    let kappa = 10.0 * (1.0 + nu) / (12.0 + 11.0 * nu);
    let exact = f * l.powi(3) / (3.0 * e0 * inertia) + f * l / (kappa * g * area);
    tip[2] / exact
}
